
[set]
FontSize = 10
Font1 = Consolas
Font2 = Arial
WinM = 0
WinX = 10
WinY = 10
WinW = 480
WinH = 202
Color = 1e
indexSort = 1
SortOrder = 1
align = 1
; ignore = ABFGHI
ForceLang = 0
Grid = 0
AutoDirtyBit = 1
; ExeAfter = "C:\Program Files\AIMP\AIMP.exe" "C:\Windows\Media\Windows Logon.wav"
; ExeAfter = shutdown.exe -r -t 0
[color]
color = 1
bg = ffffee
fg = 0
bgh = ffffbb
fgh = 0
border = 999900
